public class LDMain {
    public static void main(String[] args) {
        LDList lista = new LDList();
        lista.addFirst(1);
        lista.addFirst(2);
        lista.addFirst(3);
        System.out.println("pierwszy: "+lista.peekFirst());
        System.out.println("ostatni: "+lista.peekLast());
        System.out.println("isElement(2): "+lista.isElement(2));
        lista.show();
        lista.showReverse();
        lista.addLast(4);
        lista.addLast(5);
        lista.addLast(6);
        lista.show();
        lista.showReverse();
        System.out.println("pierwszy: "+lista.peekFirst());
        System.out.println("ostatni: "+lista.peekLast());
        System.out.println("isElement(4): "+lista.isElement(4));
        System.out.println("pollFirst: "+lista.pollFirst());
        lista.show();
        lista.showReverse();
        System.out.println("pollLast: "+lista.pollLast());
        System.out.println("isElement(6): "+lista.isElement(6));
        lista.show();
        lista.showReverse();
        System.out.println("pollFirst: "+lista.pollFirst());
        System.out.println("isElement(3): "+lista.isElement(3));
        lista.show();
        lista.showReverse();
        System.out.println("pollLast: "+lista.pollLast());
        System.out.println("isElement(5): "+lista.isElement(5));
        lista.show();
        lista.showReverse();
        System.out.println("addFirst(7)");
        System.out.println("addLast(8)");
        lista.addFirst(7);
        lista.addLast(8);
        lista.show();
        lista.showReverse();
        System.out.println("removeByValue(7)");
        lista.removeByValue(7);
        lista.show();
        lista.showReverse();
        System.out.println("removeByValue(4)");
        lista.removeByValue(4);
        lista.show();
        lista.showReverse();
        System.out.println("removeByValue(1)");
        lista.removeByValue(1);
        lista.show();
        lista.showReverse();
    }
}
